@echo off
REM Setup script for Mouse Mover on Windows
REM This script creates a convenient way to run mouse mover from anywhere

echo ========================================
echo     Mouse Mover Setup for Windows
echo ========================================
echo.

REM Get the directory where this script is located
set "SCRIPT_DIR=%~dp0"
REM Remove trailing backslash
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

REM Check for admin rights (optional, but recommended for PATH modification)
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo Note: Running without administrator privileges.
    echo The script will create a batch file in the current directory instead of modifying PATH.
    echo For system-wide installation, run this script as Administrator.
    echo.
)

echo This setup will:
echo 1. Create a 'msmvr.bat' command file
echo 2. Optionally add it to your PATH for easy access
echo.

REM Create a wrapper batch file
echo Creating msmvr.bat wrapper...
(
echo @echo off
echo REM Mouse Mover wrapper - auto-generated by setup
echo call "%SCRIPT_DIR%\run_mouse_mover.bat" %%*
) > "%SCRIPT_DIR%\msmvr.bat"

echo msmvr.bat created successfully!
echo.

REM Ask user if they want to add to PATH
set /p ADD_TO_PATH="Would you like to add Mouse Mover to your PATH? (y/n): "

if /i "%ADD_TO_PATH%"=="y" (
    echo.
    echo Adding to PATH...
    
    REM Check for admin rights again
    net session >nul 2>&1
    if %errorlevel% neq 0 (
        echo.
        echo ERROR: Administrator privileges required to modify PATH.
        echo.
        echo Please either:
        echo 1. Run this script as Administrator, OR
        echo 2. Manually add this directory to your PATH: %SCRIPT_DIR%
        echo    - Open System Properties
        echo    - Click Environment Variables
        echo    - Edit the PATH variable
        echo    - Add: %SCRIPT_DIR%
        echo.
        echo Alternatively, you can copy msmvr.bat to a directory already in your PATH.
    ) else (
        REM Add to system PATH (requires admin)
        setx /M PATH "%PATH%;%SCRIPT_DIR%" >nul 2>&1
        if %errorlevel% eq 0 (
            echo Successfully added to system PATH!
            echo You may need to restart your command prompt for changes to take effect.
        ) else (
            REM Fallback to user PATH if system PATH fails
            setx PATH "%PATH%;%SCRIPT_DIR%" >nul 2>&1
            echo Added to user PATH.
            echo You may need to restart your command prompt for changes to take effect.
        )
    )
) else (
    echo.
    echo Skipping PATH modification.
    echo To run Mouse Mover, either:
    echo 1. Navigate to %SCRIPT_DIR% and run: msmvr.bat
    echo 2. Run with full path: "%SCRIPT_DIR%\msmvr.bat"
    echo 3. Double-click run_mouse_mover.bat in Windows Explorer
)

echo.
echo ========================================
echo          Setup Complete!
echo ========================================
echo.
echo You can now run Mouse Mover by:
if /i "%ADD_TO_PATH%"=="y" (
    echo - Opening a new command prompt and typing: msmvr
) else (
    echo - Running: "%SCRIPT_DIR%\msmvr.bat"
    echo - Or double-clicking run_mouse_mover.bat
)
echo.
echo To test the installation, run: msmvr.bat
echo.
pause
